language: node_js
node_js:
  - "8"

before_install:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git config --global push.default simple
  - git remote set-url origin https://${GH_TOKEN}@github.com/Multicaja/api.git

before_script:
  - curl -L "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/shunit2/shunit2-2.1.6.tgz" | tar zx
  - npm install -g spectacle-docs
  - npm install -g redoc-cli
  - npm install -g base64-js
  - npm install -g builtin-status-codes
  - npm install -g ieee754
  - npm install -g to-arraybuffer
  - npm install -g xtend

script:
  # Get proper branch name based on http://graysonkoonce.com/getting-the-current-branch-name-during-a-pull-request-in-travis-ci/
  - export PR=https://api.github.com/repos/$TRAVIS_REPO_SLUG/pulls/$TRAVIS_PULL_REQUEST
  - export BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
  # All variables ready - run the test script
  - bash api-spec_validation_test.sh
  - spectacle --target-dir docs-fenden --target-file fenden-api.html fenden-api.yml
  - redoc-cli bundle -o fenden-api-redoc.html fenden-api.yml

  - mv docs-fenden/fenden-api.html .

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: docs
  verbose: true
  on:
    branch: master